#============= Realistic Food =============#
#~Jacklin213 ©LinCraft/LinProductions 2013

#Checks for updates on startup
UpdateCheck: true

#Settings for ever food item (At default value)
Food:
  #Example
  #Apple:
  #  heal: hunger/health
  #  modifier: 1-20 (2 for one bar)
  Apple:
    heal: hunger
    modifier: 8
  BakedPotato:
    heal: hunger
    modifier: 12
  Bread:
    heal: hunger
    modifier: 10
  #Cake slice
  Cake:
    heal: hunger
    modifier: 4
  Carrot:
    heal: hunger
    modifier: 8
  CookedChicken:
    heal: hunger
    modifier: 12
  CookedFish:
    heal: hunger
    modifier: 10
  CookedPorkchop:
    heal: hunger
    modifier: 16
  Cookie:
    heal: hunger
    modifier: 4
  GoldenApple:
    heal: health
    modifier: 8
  GoldenCarrot:
    heal: health
    modifier: 12
  Melon:
    heal: hunger
    modifier: 4
  MushroomStew:
    heal: hunger
    modifier: 12
  PoisonousPotato:
    heal: hunger
    modifier: 4
  Potato:
    heal: hunger
    modifier: 2
  PumpkinPie:
    heal: hunger
    modifier: 16
  RawBeef:
    heal: hunger
    modifier: 6
  RawChicken:
    heal: hunger
    modifier: 4
  RawFish:
    heal: hunger
    modifier: 4
  RawPorkchop:
    heal: hunger
    modifier: 6
  RottenFlesh:
    heal: hunger
    modifier: 8
  SpiderEye:
    heal: hunger
    modifier: 4
  Steak:
    heal: hunger
    modifier: 16